name: spending_management_app


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_bottom_navigation_bar: ^1.3.3
  font_awesome_flutter: ^10.8.0
  fl_chart: ^0.69.2
  intl: ^0.17.0
  google_sign_in: ^6.2.2
  flutter_colorpicker: ^1.1.0
  image_picker: ^1.1.2

  firebase_core: ^3.8.1

  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  cloud_firestore: ^5.6.0
  dotted_border: ^2.1.0

  calendar_agenda:
    path: dev_lib/calendar_agenda

  expense_repository:
      path: packages/expense_repository



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
